### ISSUE TITLE
Doesn't work correctly

### ISSUE THREAD

**Issue by HumanTree92** [ESX-PUBLIC/esx_thief#10]
When i press Key X nothing happens. No handsup or anything. But when i press Key G my hands go up??? Its set to use Key X not G

**Comment by patriktjern** [comment]
Same here, also the hands go up and down like a bird when its about to start flying lul.

**Comment by HumanTree92** [comment]
The problem with the Hands up not working for me was the fact that i rebinded my duck key to G instead of X.

**Comment by KrizKhaoz** [comment]
had an issue when I put my hands up using X it would put them up and down super fast as if it was continuously attempting to toggle the button even if it was held
