### ISSUE TITLE
Error Resuming coroutine

### ISSUE THREAD

**Issue by x0Z3ro0x** [ESX-PUBLIC/esx_thief#11]
Error resuming coroutine: handsup.lua:26: attempt to call a nil value (global 'RequestAnimDict')
stack traceback:
        handsup.lua:26: in function <handsup.lua:21>

**Comment by HawaiiBeach** [comment]
Fixed in de4fa2f446ef8266ef8ab47444b13e829dd1c009 don't ask me why it was clearfied as a server script FailFish
