### ISSUE TITLE
Menu is only 1ms open

### ISSUE THREAD

**Issue by EGUltraTM** [ESX-PUBLIC/esx_thief#13]
When i press G when the mate has his hands up its only 1ms open and closes instantly.

**Comment by PuukoSpede** [comment]
same

**Comment by lrh1290** [comment]
its because you have to lower your weapon first for the menu to pop up. so you must simultaneously press the mug button and release of your ads key (would be cool if this could be fixed btw because alot of players run as soon as you lower your weapon)

**Comment by delduwaht** [comment]
Menus just close automaticaly when you press the right-click button.
