### ISSUE TITLE
When I press "X", he raises his arm quickly and then lowers. How do I fix it?

### ISSUE THREAD

**Issue by Opiez** [ESX-PUBLIC/esx_thief#4]
When I press "X", he raises his arm quickly and then lowers. How do I fix it?

**Comment by HawaiiBeach** [comment]
Happens me aswell, i'll have to take a closer look

**Comment by Opiez** [comment]
If you can fix it, let me know! Thanks

**Comment by InZidiuZ** [comment]
Did anyone manage to fix it?
